language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - nightly

before_script:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover=coverage/coverage.xml --configuration=tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls
